# Generated by Django 5.1.3 on 2024-11-08 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applica', '0002_conductor_dni'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conductor',
            name='dni',
            field=models.CharField(max_length=12, unique=True),
        ),
    ]
