# Generated by Django 5.1.3 on 2024-11-08 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applica', '0004_alter_revisiontecnica_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='revisiontecnica',
            name='observaciones',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Observaciones'),
        ),
    ]
