# Generated by Django 5.1.3 on 2024-11-08 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applica', '0005_alter_revisiontecnica_observaciones'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidencia',
            name='descripcion',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Descripcion'),
        ),
    ]
