# Generated by Django 5.1.3 on 2024-11-11 19:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applica', '0006_alter_incidencia_descripcion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Soat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_actualizacion', models.DateField()),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='applica.vehiculo')),
            ],
            options={
                'unique_together': {('vehiculo',)},
            },
        ),
    ]
